run:
  tests: true
  timeout: 5m
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - copyloopvar
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gocognit
    - nestif
    - prealloc
    - testpackage
linters-settings:
  lll:
    line-length: 160
  funlen:
    lines: 120
    statements: 50
  goimports:
    local-prefixes: github.com/k6zma/DockerMonitoringApp/pinger
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
  gocognit:
    min-complexity: 35

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - funlen
        - dupl

    - linters:
        - gocritic
      text: 'hugeParam\: \S+ is heavy \(\d+ bytes\)\; consider passing it by pointer'
